### ISSUE TITLE
Address 1.1 review feedback

### ISSUE THREAD

**Issue by pixelky** [CS2103-AY1819S1-W16-1/main#44]
Modify (or remove) the top navigation bar on Github pages.
Update (or remove) the badges on top of README to point to our repo's status
Add coming in v2.0 to features that hasn't been implemented yet in User Guide

**Comment by pixelky** [comment]
Increase size of certain photos in AboutUs

**Comment by ericyjw** [comment]
which photo is the desired size? Javen, yours and mine?
